# Site settings
course_name: Introduction to High Performance Computing
course_description: "How are airplanes built without a physical prototype? How do we understand the evolution of the universe, or how are new cancer treatments identified for initial testing? Big problems require big computers - this course is meant to provide a general introduction to high performance computing and its role in today's world. This course will discuss the components of supercomputers, how they are organized, and the challenges in developing massive heterogeneous systems."
course_semester: "Spring 2024"

url: https://www.evl.uic.edu # the base hostname & protocol for your site
baseurl: /papka/cs494 # the subpath of your site, e.g. /blog/
last_updated: true # set to true if you want to display last updated in the footer

schoolname: "University of Illinois Chicago"
schoolurl: "https://www.uic.edu"
blackboard: "https://uic.blackboard.com"
department: "https://www.cs.uic.edu"
#twitter_username: mpapka
#github_username: mpapka
#google_scholar_id: pQwfBFwAAAAJ # your Google Scholar ID
#orcid_id: 0000-0002-6418-5767 # your ORCID ID

address: |
    Department of Computer Science
    University of Illinois Chicago
    Chicago, IL 60607

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
google_analytics: G-RDB7MC9C75

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax

# Other options
permalink: pretty
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    projects:
        output: true
    announcements:
        output: false
    galleries:
        output: true

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "lectures"
    values:
      layout: "lecture"


# Includes & excludes
exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - vendor

# -----------------------------------------------------------------------------
# Jekyll Link Attributes
# -----------------------------------------------------------------------------

# These are the defaults
external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank
  exclude: